#!/bin/bash
cp noflag.gif AD.gif
cp noflag.gif AI.gif
cp noflag.gif AQ.gif
cp noflag.gif AG.gif
cp noflag.gif BV.gif
cp noflag.gif CX.gif
cp noflag.gif CC.gif
cp noflag.gif KM.gif
cp noflag.gif DJ.gif
cp noflag.gif DM.gif
cp noflag.gif SV.gif
cp noflag.gif AE.gif
cp noflag.gif UM.gif
cp noflag.gif FK.gif
cp noflag.gif FX.gif
cp noflag.gif GM.gif
cp noflag.gif GS.gif
cp noflag.gif GH.gif
cp noflag.gif GD.gif
cp noflag.gif GN.gif
cp noflag.gif GW.gif
cp noflag.gif GQ.gif
cp noflag.gif GF.gif
cp noflag.gif HM.gif
cp noflag.gif HN.gif
cp noflag.gif KW.gif
cp noflag.gif LA.gif
cp noflag.gif LS.gif
cp noflag.gif LR.gif
cp noflag.gif LI.gif
cp noflag.gif MW.gif
cp noflag.gif MV.gif
cp noflag.gif ML.gif
cp noflag.gif MT.gif
cp noflag.gif MH.gif
cp noflag.gif MQ.gif
cp noflag.gif MU.gif
cp noflag.gif MR.gif
cp noflag.gif YT.gif
cp noflag.gif FM.gif
cp noflag.gif MM.gif
cp noflag.gif NI.gif
cp noflag.gif NE.gif
cp noflag.gif NG.gif
cp noflag.gif NU.gif
cp noflag.gif UZ.gif
cp noflag.gif PW.gif
cp noflag.gif PG.gif
cp noflag.gif PN.gif
cp noflag.gif DO.gif
cp noflag.gif RE.gif
cp noflag.gif RW.gif
cp noflag.gif EH.gif
cp noflag.gif KN.gif
cp noflag.gif SH.gif
cp noflag.gif SM.gif
cp noflag.gif VC.gif
cp noflag.gif AS.gif
cp noflag.gif GS.gif
cp noflag.gif ST.gif
cp noflag.gif SN.gif
cp noflag.gif SC.gif
cp noflag.gif SR.gif
cp noflag.gif SJ.gif
cp noflag.gif SZ.gif
cp noflag.gif TJ.gif
cp noflag.gif TD.gif
cp noflag.gif IO.gif
cp noflag.gif TF.gif
cp noflag.gif TK.gif
cp noflag.gif TM.gif
cp noflag.gif VU.gif
cp noflag.gif WF.gif
cp noflag.gif ZR.gif
cp noflag.gif ZM.gif

